version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS: redis:6379
    networks:
      - network
    restart: unless-stopped
  
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    networks:
      - network

networks:
  network: